### ISSUE TITLE
1.9 implement social network api to recommend products

### ISSUE THREAD

**Issue by kajogo777** [AmalHany/FBO#54]

**Comment by kajogo777** [comment]
@AmalHany 
please tell me if this is the required format

**Comment by AmalHany** [comment]
This is correct. But I recommend that you change the "#" so it doesn't cause a confusion since github uses it to tag/refer to an issue.
You can also write in the description of the issue the full user story.

**Comment by kajogo777** [comment]
@Swailem95 
review b3d eznak 💃
